# Generated by Django 3.2.7 on 2022-03-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user'))),
                ('type', models.CharField(choices=[('1', 'Sell'), ('2', 'Rent')], default='Sell', max_length=20)),
                ('published', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('1', 'Andhra Pradesh'), ('2', 'Delhi')], max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availibility', models.CharField(choices=[('1', 'Immediately'), ('2', 'In 15 days'), ('3', 'In a month')], max_length=20)),
                ('bathroom', models.IntegerField()),
                ('garage', models.BooleanField(null=True)),
                ('gym', models.BooleanField(null=True)),
                ('swimming_pool', models.BooleanField(null=True)),
                ('furnishing', models.CharField(choices=[('1', 'Fully Furnished'), ('2', 'Semi Furnished'), ('3', 'Unfurnished')], max_length=20, null=True)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
