# Generated by Django 3.2.7 on 2022-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20220320_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
