# Generated by Django 3.2.7 on 2022-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220320_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(default='h1.jpg', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', 'Uttar Pradesh'), ('4', 'Delhi')], max_length=20),
        ),
    ]
