# Generated by Django 3.2.7 on 2022-04-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220404_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='sqft',
        ),
    ]
