# Generated by Django 3.2.7 on 2022-04-10 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_remove_property_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='availibility',
            field=models.CharField(choices=[('1', 'Ready to move'), ('2', 'In 15 days'), ('3', 'In a month')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', ' New Delhi'), ('4', 'Maharashtra'), ('5', 'Tamil Nadu'), ('6', 'Uttar Pradesh'), ('7', 'Uttrakhand'), ('7', 'Uttrakhand')], max_length=20),
        ),
    ]
