# Generated by Django 3.2.7 on 2022-04-06 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user_id',
            field=models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
